 %Author: Timothy Rokebrand
%The following code produces the GUI for the user to interact with
%this iteration focuses on design from scratch it does not yet include
%the option of adding pre-designed antennas

%This file creates the main menu and the graphics handles from this menu
%store the necessary information in order to pass and manipulate, the process
%of handling data differs between this and scripting methods 

clear all
addpath('../geometryDefs/');
addpath('../plotFunctions');
addpath('../writeNEC');
addpath('../writeFeko');

screenSize = get(0, 'MonitorPositions');
main_window.fig = figure('NumberTitle','off','name', 'RCsim','position', [100 100 900 675],...
 'color',[0.94 0.94 0.94], 'Resize', 'off');
sizer = get(main_window.fig, 'position');
main_window.axes = axes('Units', 'Pixels',...
 'position', [sizer(4)*0.1 sizer(4)*0.25 sizer(3)*0.45 sizer(4)*0.5],...
 'XlimMode', 'manual','YlimMode', 'manual', 'ZlimMode', 'manual',...
 'xlabel', 'X', 'ylabel', 'Y', 'zlabel', 'Z', 'view', [-60, 48]);
 
main_window.simulation_button = uicontrol('style','pushbutton',...
'string', 'Simulation Information','UserData',...
  struct('frequency_start',300,'frequency_increment',0,...
  'frequency_steps',1,'ground_flag',0,'rad_theta_start',0,...
  'rad_phi_start',0,'rad_resolution',5,'rad_theta_steps',9,...
    'rad_phi_steps',5,'rad_theta_end',360,'rad_phi_end',180),...
'position', [sizer(3)*0.55 sizer(4)*0.65 sizer(3)*0.45 40]);

main_window.add_element_button = uicontrol('style','pushbutton',...
'string', 'Add Element',...
'position', [sizer(3)*0.55 sizer(4)*0.55 sizer(3)*0.45 40]); 
 
main_window.remove_element_button = uicontrol('style','pushbutton',...
'string', 'Remove Element','position', [sizer(3)*0.55 sizer(4)*0.45 ...
sizer(3)*0.45 40]);
main_window.simulate_button = uicontrol('style','pushbutton',...
'string', 'Simulate','callback', {@simulate_callback,main_window},...
'position', [sizer(3)*0.55 sizer(4)*0.25 sizer(3)*0.45 40]);  
set(main_window.add_element_button, 'Callback', {@add_element_window, main_window,main_window.fig});
set(main_window.simulation_button, 'Callback', {@simulation_setup, main_window});
